### ISSUE TITLE
Missing "Rows gap" option for code components with "Vertical stack" style

### ISSUE THREAD

**Issue by donalffons** [plasmicapp/plasmic#82]
When I add a "Vertical stack" element in Plasmic studio, I have the usual option for "Rows gap":
![image](https://github.com/plasmicapp/plasmic/assets/33040347/37f7b00f-7933-4926-a094-113c41511cc4)
This is what I want.

However, with any code component (created via `PLASMIC.registerComponent` and `styleSections: true`), the option is missing.
![image](https://github.com/plasmicapp/plasmic/assets/33040347/01a29984-5481-4103-9c40-8ca9e035a104)

My current work-around is to change the layout to "Document layout"...
![image](https://github.com/plasmicapp/plasmic/assets/33040347/f9740a50-3a29-47fd-9f89-11fe525468c3)

...then set a value for "Gap" there...
![image](https://github.com/plasmicapp/plasmic/assets/33040347/80260b28-ee58-4dd4-82ed-eab07654243d)

...and then revert back to "Vertical stack"...
![image](https://github.com/plasmicapp/plasmic/assets/33040347/9564bcf4-64f4-492a-8d4c-c29f9a9314e8)

...which preserves the "Gap" value in my component's styles - although it is now invisible.
![image](https://github.com/plasmicapp/plasmic/assets/33040347/e02bf80e-7542-4487-bdd2-08c7845a19cf)

I think it would be great if a "Gap" field would be available in this case.

PS: Loving the progress you've been making on Plasmic :slightly_smiling_face:.

**Comment by yang** [comment]
Wow, that is a crazy ninja workaround! Kudos on finding that.

Yes, we really should allow standard flex Gap here...

Normally we polyfill flex Gap because it's still not quite as widely compatible with some mobile Safari versions that are still in significant numbers. But we can't do this for code components because these are arbitrary user supplied components. But we should probably just allow it anyway, and possibly provide warnings about it that you can dismiss.

**Comment by chungwu** [comment]
Actually we just pushed an update to enable setting flex gap on code components!  It will be the css-only, non-polyfilled variety.

**Comment by donalffons** [comment]
Thanks a lot!
